import type { Metadata } from 'next';
import { Karla } from 'next/font/google';
import './globals.css';

import { FooterWrapper, HeaderWrapper } from './components/HeaderWrapper';
import ToastProvider from './components/ToastProvider';

const karla = Karla({
  weight: '400',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Upskills',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${karla.className} antialiased`}>
        <ToastProvider />
        <HeaderWrapper />
        <main>{children}</main>
        <FooterWrapper />
      </body>
    </html>
  );
}
