import type { Metadata } from 'next';
import { Karla } from 'next/font/google';
import './globals.css';
import { Toaster } from 'react-hot-toast';
import { FooterWrapper, HeaderWrapper } from './component/HeaderWrapper';

const karla = Karla({
  weight: '400',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Upskill',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${karla.className} antialiased`}>
        <Toaster position="top-right" toastOptions={{ duration: 2000 }} />
        <HeaderWrapper />
        <main>{children}</main>
        <FooterWrapper />
      </body>
    </html>
  );
}
